### ISSUE TITLE
Slammed with Lock(bot) messages in email

### ISSUE THREAD

**Issue by KeithBarrows** [devbotsxyz/lock-issue#1]
Is there a way to add a flag to NOT send email to the distro?  I am getting several hundred a day from 1 repo and now the noise to signal ratio is all noise.  Makes the email list worthless.

**Comment by thadiun** [comment]
@KeithBarrows apologies for responding to this so late, but it is unclear what happened here. Can you point me to a repository where you use the `lock-issues` bot so that I can investigate and get back with a good answer?

**Comment by KeithBarrows** [comment]
Heh.  I'm trying to remember now.
